In [4]:
#day5 practice 
import numpy as np
np.__version__


'1.20.3'

In [7]:
vector_row = np.array([1,2,3]) # 1차원 행터
vector_row

array([1, 2, 3])

In [13]:
vector_column = np.array([[1],
                          [2],
                          [3]]) #밖[] 안에 있는것 3개 그 안에 [] 안에 있는것 1개 
vector_column
vector_column.shape # 3,1 3행 1열 

(3, 1)

In [15]:
print(type(vector_row)) # 클래스 출력  

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_10052/2886584256.py, line 1)

In [21]:
temp = np.ndarray((3,)) # 랜덤한 수를 추출해 만드렁 주지만 권장 x
temp

array([9.34609790e-307, 6.23037657e-307, 8.90104239e-307])

In [27]:
A = np.mat('[1 2 5;3 4 6;7 8 9]') # 2차원 매트릭스 ';' 로 행 단위 구분 
A

matrix([[1, 2, 5],
        [3, 4, 6],
        [7, 8, 9]])

In [29]:
A.T # transpose 한것 줄력 

matrix([[1, 3, 7],
        [2, 4, 8],
        [5, 6, 9]])

In [51]:
from scipy import linalg  # linalg  역핼렬 , 행력 값 등을 구해줍

linalg.inv(A) # inv invers 값 
linalg.det(A) # det 행렬식 값 산출 

value, vector=linalg.eig(A) # eigenvalue, eigenvector  고유값과 고유백터 

value # 고유값 , 
vector # 고유 벡터 

u, s, vt = linalg.svd(A) # 특이값 분해 Singular Value Decomposition 
s

A.dot(A) # 내적 의미 

matrix([[ 42,  50,  62],
        [ 57,  70,  93],
        [ 94, 118, 164]])

In [56]:
rend_vec = np.empty((2,3,2)) # 3차원 2, 2차원 3, 1차원 2 임의값
rend_vec

array([[[9.21003679e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.13073288e+277, 1.60469626e-051]],

       [[2.92804584e-057, 5.74387041e+174],
        [2.74261703e-057, 2.03857435e+160],
        [3.85663882e-057, 2.14786771e+184]]])

In [ ]:
zero_mat = np.zeros((3,2)) # 0 g행열

In [ ]:
one_matrix = np.ones((3,2)) # 1행렬

In [58]:
num_mat = np.full((2,2,2), 7) # 전체 에 7을 채워 넣습니다.
num_mat

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [64]:
# 희소 행렬 만들기 0이 많은 행렬로 
from scipy import sparse 

temp = np.array([[0,0],
                [0,1],
                [3,0]])
# CSR (compressed sparse row) 행렬
csr_mat = sparse.csr_matrix(temp)
print(csr_mat)

  (1, 1)	1
  (2, 0)	3


In [71]:
# 원소추출
A = np.mat('[1 2 5;3 4 6;7 8 9]') # 2차원 매트릭스 ';' 로 행 단위 구분 

A[2] # 2행 출력 
A[2,1] # 2행 1열 출력 
A[:] #원소 전체 출력 

matrix([[1, 2, 5],
        [3, 4, 6],
        [7, 8, 9]])

In [74]:
A.shape #원소 차원 확인 
A.size # 원소 갯수 
A.ndim # 차원 수1
np.max(A, axis=0) # axis기준은 행인데 1열의 1행2행3행에서의 최대 값 즉, 각열의 최대값
np.max(A, axis=1) # axis기준은 열인데 1행의 1열2열3열에서의 최대 값 즉, 걱행의 최대값


np.var(A) #분산
np.std(A) # 표준편차
np.mean(A) # 평균


2.581988897471611

In [76]:
# 4x3 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# 2x6 행렬로 크기를 바꿉니다.
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [79]:
matrix.flatten() # 메트릭스 펼치기 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

NameError: name 'np' is not defined

In [ ]:
# 5_2 maxrix compytation

In [14]:
import numpy as np

from scipy import linalg

A = np.array([[1, 1, 1],
              [1, 1, 10],
              [1, 1, 15]])

np.linalg.matrix_rank(A) # 랭그 구하기 
A.diagonal() # 대각 원소 반환
A.diagonal().copy() # 반환 행렬 배열 변환 위한 복사 
A.trace() # 대각합 계산


array([ 1,  1, 15])

In [15]:
A @ A # 행열 곱 입니다 @


array([[  3,   3,  26],
       [ 12,  12, 161],
       [ 17,  17, 236]])

In [16]:
A*A  # 해당 원소끼리의 곱입니다  주의! 

array([[  1,   1,   1],
       [  1,   1, 100],
       [  1,   1, 225]])

In [20]:
# SVD 정확하게 
U,s , Vh = linalg.svd(A)
M,N = A.shape
Sig = linalg.diagsvd(s,M,N)
U.shape, s.shape, Vh.shape, Sig

((3, 3),
 (3,),
 (3, 3),
 array([[1.81705983e+01, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.35253727e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 1.72734140e-16]]))

In [21]:
# 난수 생성입니다. 
np.random.seed(0) # 초깃값 지정

np.random.random(3) # 0~1.0 사이의 세개의 실수 난수생성 

array([0.5488135 , 0.71518937, 0.60276338])

In [38]:
np.random.randint(0,11,3) # 0이상와 11미만 사이의 정수 난수 3개 생성

array([0, 0, 4])

In [39]:
np.random.normal(0.0,1.0,3) # 평균이 0 표준평차 1.0 정규분포 세개의 수 

array([1.46274045, 1.53502913, 0.56644004])

In [40]:
np.random.logistic(0.0,1.0,3)# 평균 0, 스케일이 1인 로지스틱분포에서 세개의 수 봅은

array([ 0.76214981, -0.57750063, -0.25321656])

In [41]:
# 1.0보다 크거나 같고 2.0보다 작은 세 개의 수를 뽑습니다.
np.random.uniform(1.0, 2.0, 3)

array([1.6976312 , 1.06022547, 1.66676672])